slint::slint!(export { Virtuoso } from "src/slint/main.slint";);

pub const LAYOUT_1920X480 : Layout = Layout {
    background: RectangleProperties {
        x: 0,
        y: 0,
        width: 1920,
        height: 480,
        radius: 0,
    },
    score_l_l: TextProperties {
        x: 0,
        y: 48,
        width: 240,
        height: 432,
        font_size: 500,
    },
    score_l_r: TextProperties {
        x: 240,
        y: 48,
        width: 240,
        height: 432,
        font_size: 500,
    },
    score_r_l: TextProperties {
        x: 1440,
        y: 48,
        width: 240,
        height: 432,
        font_size: 500,
    },
    score_r_r: TextProperties {
        x: 1681,
        y: 48,
        width: 240,
        height: 432,
        font_size: 500,
    },
    epee: TextProperties {
        x: 860,
        y: 380,
        width: 200,
        height: 100,
        font_size: 80,
    },
    sabre: TextProperties {
        x: 1060,
        y: 380,
        width: 200,
        height: 100,
        font_size: 80,
    },
    fleuret: TextProperties {
        x: 660,
        y: 380,
        width: 200,
        height: 100,
        font_size: 80,
    },
    auto_score_status: TextProperties {
        x: 510,
        y: 400,
        width: 120,
        height: 80,
        font_size: 32,
    },
    auto_timer_status: TextProperties {
        x: 1290,
        y: 400,
        width: 120,
        height: 80,
        font_size: 32,
    },
    prioriry_l_cap: TextProperties {
        x: 525,
        y: 276,
        width: 55,
        height: 144,
        font_size: 120,
    },
    priority_l_text: TextProperties {
        x: 550,
        y: 360,
        width: 80,
        height: 44,
        font_size: 36,
    },
    priority_r_cap: TextProperties {
        x: 1305,
        y: 276,
        width: 55,
        height: 144,
        font_size: 120,
    },
    priority_r_text: TextProperties {
        x: 1330,
        y: 360,
        width: 80,
        height: 44,
        font_size: 36,
    },
    caution_l_rect: RectangleProperties {
        x: 520,
        y: 244,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 520,
        y: 244,
        width: 100,
        height: 44,
        font_size: 36,
    },
    penalty_l_rect: RectangleProperties {
        x: 520,
        y: 192,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_l_text: TextProperties {
        x: 520,
        y: 192,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_l_bot_rect: RectangleProperties {
        x: 520,
        y: 132,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_bot_text: TextProperties {
        x: 520,
        y: 132,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passice_l_top_rect: RectangleProperties {
        x: 520,
        y: 80,
        width: 100,
        height: 44,
        radius: 10,
    },
    passice_l_top_text: TextProperties {
        x: 520,
        y: 80,
        width: 100,
        height: 44,
        font_size: 36,
    },
    caution_r_rect: RectangleProperties {
        x: 1300,
        y: 244,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1300,
        y: 244,
        width: 100,
        height: 44,
        font_size: 36,
    },
    penalty_r_rect: RectangleProperties {
        x: 1300,
        y: 192,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_r_text: TextProperties {
        x: 1300,
        y: 192,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_r_bot_rect: RectangleProperties {
        x: 1300,
        y: 132,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_bot_text: TextProperties {
        x: 1300,
        y: 132,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_r_top_rect: RectangleProperties {
        x: 1300,
        y: 80,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_top_text: TextProperties {
        x: 1300,
        y: 80,
        width: 100,
        height: 44,
        font_size: 36,
    },
    period: TextProperties {
        x: 628,
        y: 207,
        width: 152,
        height: 171,
        font_size: 200,
    },
    passive_counter_dec: TextProperties {
        x: 628,
        y: 69,
        width: 76,
        height: 140,
        font_size: 160,
    },
    passive_counter_sec: TextProperties {
        x: 704,
        y: 69,
        width: 76,
        height: 140,
        font_size: 160,
    },
};
