slint::slint!(export { Virtuoso } from "src/slint/main.slint";);

pub const LAYOUT_1920X480 : Layout = Layout {
    background: RectangleProperties {
        x: 0,
        y: 0,
        width: 1920,
        height: 480,
        radius: 0,
    },
    score_l_l: TextProperties {
        x: 0,
        y: 48,
        width: 240,
        height: 432,
        font_size: 500,
    },
    score_l_r: TextProperties {
        x: 240,
        y: 48,
        width: 240,
        height: 432,
        font_size: 500,
    },
    score_r_l: TextProperties {
        x: 1440,
        y: 48,
        width: 240,
        height: 432,
        font_size: 500,
    },
    score_r_r: TextProperties {
        x: 1681,
        y: 48,
        width: 240,
        height: 432,
        font_size: 500,
    },
    epee: TextProperties {
        x: 860,
        y: 380,
        width: 200,
        height: 100,
        font_size: 80,
    },
    sabre: TextProperties {
        x: 1060,
        y: 380,
        width: 200,
        height: 100,
        font_size: 80,
    },
    fleuret: TextProperties {
        x: 660,
        y: 380,
        width: 200,
        height: 100,
        font_size: 80,
    },
    auto_score_status: TextProperties {
        x: 486,
        y: 400,
        width: 120,
        height: 80,
        font_size: 32,
    },
    auto_timer_status: TextProperties {
        x: 1314,
        y: 400,
        width: 120,
        height: 80,
        font_size: 32,
    },
    prioriry_l_cap: TextProperties {
        x: 501,
        y: 276,
        width: 55,
        height: 144,
        font_size: 120,
    },
    priority_l_text: TextProperties {
        x: 526,
        y: 360,
        width: 80,
        height: 44,
        font_size: 36,
    },
    priority_r_cap: TextProperties {
        x: 1329,
        y: 276,
        width: 55,
        height: 144,
        font_size: 120,
    },
    priority_r_text: TextProperties {
        x: 1354,
        y: 360,
        width: 80,
        height: 44,
        font_size: 36,
    },
    caution_l_rect: RectangleProperties {
        x: 496,
        y: 244,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_l_text: TextProperties {
        x: 496,
        y: 244,
        width: 100,
        height: 44,
        font_size: 36,
    },
    penalty_l_rect: RectangleProperties {
        x: 496,
        y: 192,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_l_text: TextProperties {
        x: 496,
        y: 192,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_l_bot_rect: RectangleProperties {
        x: 496,
        y: 132,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_bot_text: TextProperties {
        x: 496,
        y: 132,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_l_top_rect: RectangleProperties {
        x: 496,
        y: 80,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_l_top_text: TextProperties {
        x: 496,
        y: 80,
        width: 100,
        height: 44,
        font_size: 36,
    },
    caution_r_rect: RectangleProperties {
        x: 1324,
        y: 244,
        width: 100,
        height: 44,
        radius: 10,
    },
    caution_r_text: TextProperties {
        x: 1324,
        y: 244,
        width: 100,
        height: 44,
        font_size: 36,
    },
    penalty_r_rect: RectangleProperties {
        x: 1324,
        y: 192,
        width: 100,
        height: 44,
        radius: 10,
    },
    penalty_r_text: TextProperties {
        x: 1324,
        y: 192,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_r_bot_rect: RectangleProperties {
        x: 1324,
        y: 132,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_bot_text: TextProperties {
        x: 1324,
        y: 132,
        width: 100,
        height: 44,
        font_size: 36,
    },
    passive_r_top_rect: RectangleProperties {
        x: 1324,
        y: 80,
        width: 100,
        height: 44,
        radius: 10,
    },
    passive_r_top_text: TextProperties {
        x: 1324,
        y: 80,
        width: 100,
        height: 44,
        font_size: 36,
    },
    period: TextProperties {
        x: 604,
        y: 207,
        width: 152,
        height: 171,
        font_size: 200,
    },
    passive_counter_dec: TextProperties {
        x: 604,
        y: 69,
        width: 76,
        height: 140,
        font_size: 160,
    },
    passive_counter_sec: TextProperties {
        x: 680,
        y: 69,
        width: 76,
        height: 140,
        font_size: 160,
    },
    timer_m: TextProperties {
        x: 765,
        y: 80,
        width: 160,
        height: 292,
        font_size: 320,
    },
    timer_colon: TextProperties {
        x: 925,
        y: 80,
        width: 63,
        height: 292,
        font_size: 330,
    },
    timer_d: TextProperties {
        x: 988,
        y: 80,
        width: 160,
        height: 292,
        font_size: 330,
    },
    timer_s: TextProperties {
        x: 1148,
        y: 80,
        width: 160,
        height: 292,
        font_size: 330,
    },
    passive_indicator: RectangleProperties {
        x: 496,
        y: 24,
        width: 928,
        height: 32,
        radius: 3,
    },
    left_color_indicator: RectangleProperties {
        x: 27,
        y: 24,
        width: 268,
        height: 32,
        radius: 3,
    },
    right_color_indicator: RectangleProperties {
        x: 1625,
        y: 24,
        width: 268,
        height: 32,
        radius: 3,
    },
    left_white_indicator: RectangleProperties {
        x: 319,
        y: 24,
        width: 134,
        height: 32,
        radius: 3,
    },
    right_white_indicator: RectangleProperties {
        x: 1467,
        y: 24,
        width: 134,
        height: 32,
        radius: 3,
    },
    recording_indicator: RectangleProperties {
        x: 1258,
        y: 64,
        width: 32,
        height: 32,
        radius: 16,
    },
};
